### ISSUE TITLE
Jerneju in Gašperju ni všeč, da je barva za 100% modra in ne zelena.

### ISSUE THREAD

**Issue by zupanibla** [naceee/naceee.github.io#1]
![image](https://github.com/naceee/naceee.github.io/assets/15369311/7d1757c7-4157-4767-a546-f2c9e5ac479e)

Prosim popravi, ker me to zelo moti.

Lp

B

**Comment by naceee** [comment]
se ne strinjam, rdeče zeleno zgleda slabo in še barvno slepi potem ne morejo ločit kdo je boljši.

lp N

**Comment by gasper1234** [comment]
To pa ne drži. Zelena barva velja za eno najbolj očem prijetnih barv v spektru. Fiziološko gledano, človeško oko je najbolj občutljivo na srednji del spektra, kjer se nahaja zelena barva. Zaradi te naravne občutljivosti zelena barva ne povzroča tako močnih naprezanj oči kot nekatere druge barve. Poleg tega ima zelena barva pomirjujoč učinek in je povezana z naravnim okoljem, kot so drevesa in trave. Zato mnogi ljudje dojemajo zeleno kot barvo svežine in harmonije. V primerjavi z modro barvo, ki lahko v močnih odtenkih povzroča občutek hladnosti, je zelena bolj prizemljena in prijetna. Njena prisotnost v naravi in povezava z rastlinjem ter okoljem prispevata k pozitivni psihološki izkušnji. V oblikovanju prostora ali barvnih shemah se zelena pogosto uporablja za ustvarjanje sproščenega in uravnoteženega vzdušja. Tako da bi morali res zamenjati barvno shemo v zeleno-redčo.

LP G
