### ISSUE TITLE
Kaj je s to tabelo, ha?

### ISSUE THREAD

**Issue by zupanibla** [naceee/naceee.github.io#2]
![image](https://github.com/naceee/naceee.github.io/assets/15369311/6eef039e-d90c-4be9-a1f0-749a1baa4031)

Lp B

**Comment by naceee** [comment]
ups enkrat sem hotel dat se slikce zraven, samo sem se potem premislu... Upam da bo tako boljse

![image](https://github.com/naceee/naceee.github.io/assets/47631585/8251ef15-5d27-4b70-8a05-1d2d5a9ddafd)

lp N

**Comment by naceee** [comment]
še urejeno po točkah

![image](https://github.com/naceee/naceee.github.io/assets/47631585/0790acaa-9e7e-4e8f-bac8-a937baba8128)

lp N

**Comment by zupanibla** [comment]
Hudo! Mislim, da lahko zapremo ta issue.

Lp B
