### ISSUE TITLE
Ena igra ni vnešena

### ISSUE THREAD

**Issue by grlj** [naceee/naceee.github.io#3]
![manjka](https://github.com/naceee/naceee.github.io/assets/28658477/c8625c9b-303d-4f42-83a6-454eeb22f42a)

Prosim popravi,
lp J

**Comment by naceee** [comment]
preberi [pogoje za igranje taroka](https://github.com/naceee/naceee.github.io), s katerimi se nisi strinjal, ampak vseeno so. 
lp N
